name: momjournal
description: "Aplikasi Pencatatan Jadwal dan Journaling untuk Ibu Muda"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.6

  # Authentication
  google_sign_in: ^6.2.2

  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2

  # UI Components
  table_calendar: ^3.0.9
  fl_chart: ^0.66.0

  # Image Handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0

  # Utilities
  uuid: ^4.3.3
  intl: 0.20.2
  path: ^1.8.3
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2

  # Icons
  cupertino_icons: ^1.0.6
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  mockito: ^5.4.4

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
     - assets/images/
     - assets/images/logo/
     - assets/icons/
     - assets/images/illustrations/
     - assets/json/

  # Fonts
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 700